"""数据库模块"""

from writing_langgraph.db.connection import (
    ConflictError,
    DatabaseError,
    checkpoint_db,
    close_all_db,
    close_db,
    execute_with_retry,
    get_db,
    get_db_connection,
    get_db_path,
    init_db,
    repair_if_needed,
    transaction,
    vacuum_db,
)
from writing_langgraph.db.models import (
    Chapter,
    Character,
    CharacterRelationship,
    Item,
    ItemLog,
    MemoryChapter,
    MemoryGlobal,
    MemoryVolume,
    NovelMetadata,
    PlotThread,
    PowerChangeLog,
    PowerLevel,
    TropeTemplate,
    Volume,
    json_dumps,
    json_loads,
)

__all__ = [
    # Connection
    "get_db_connection",
    "get_db",
    "init_db",
    "transaction",
    "close_db",
    "close_all_db",
    "get_db_path",
    "execute_with_retry",
    "vacuum_db",
    "checkpoint_db",
    "repair_if_needed",
    "DatabaseError",
    "ConflictError",
    # Models
    "NovelMetadata",
    "PowerLevel",
    "Character",
    "CharacterRelationship",
    "Item",
    "PowerChangeLog",
    "ItemLog",
    "PlotThread",
    "Volume",
    "Chapter",
    "MemoryGlobal",
    "MemoryVolume",
    "MemoryChapter",
    "TropeTemplate",
    # Utils
    "json_loads",
    "json_dumps",
]
